version: "3"
services:
  api:
    build: ./api
    ports:
      - "5000:5000"
    volumes:
      - ./api:/api
  app:
    build: ./app
    command: npm run dev
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
